# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       TZ: Asia/Tokyo
#       #RAILS_MASTER_KEY: <your_master_key>
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     volumes:
#       - postgresql_data:/var/lib/postgresql
#     ports:
#       - 5432:5432
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -d my_recipe_development -U postgres"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     command: bash -c "bundle install && bin/rails db:prepare && rm -f tmp/pids/server.pid && bin/rails s -b 0.0.0.0 -p 3000"
#     tty: true
#     stdin_open: true
#     volumes:
#       - .:/myapp
#       #- ./config/master.key:/myapp/config/master.key
#     environment:
#       TZ: Asia/Tokyo
#     ports:
#       - "3000:3000"
#     depends_on:
#       db:
#         condition: service_healthy

# volumes:
#   postgresql_data:
services:
  db:
    image: postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d my_recipe_development -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && bundle exec rails db:prepare && rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/myapp/node_modules
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  bundle_data:
  postgresql_data:
  node_modules: