default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: my_recipe_development

test:
  <<: *default
  database: my_recipe_test

production:
  <<: *default
  database: my_recipe_production
  username: my_recipe
  password: <%= ENV["MY_RECIPE_DATABASE_PASSWORD"] %>
